name: mime_type
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog:
    git:
      url: https://github.com/jxstxn1/dart_frog/
      path: packages/dart_frog
      ref: main

  path: ^1.8.3

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
